
skmswhrdavferojbocdz = "skmswhrdavferojbocdz"

[functions.create-organization]
verify_jwt = true

[functions.get-service-role]
verify_jwt = true

[functions.update-dealership]
verify_jwt = true

[functions.update-profile]
verify_jwt = true
