// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skmswhrdavferojbocdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrbXN3aHJkYXZmZXJvamJvY2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDYwOTcsImV4cCI6MjA2MDIyMjA5N30.xZ-R40vMSodQ7qHWHw3Rxvum3WDCkxoUcs66SIoeVRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);